---
  - name:
    hosts: localhost
    connection: local
    gather_facts: False
    vars_files:
    - group_vars/all.yml
    tasks:
      - name:   provision AWS infrastructure and deploy wordpress
        cloudformation:
          stack_name: "{{ stack_name }}"
          state: "present"
          region: "{{ region_name }}"
          disable_rollback: false 
          template: "files/wordpress_deployment.json"
        register: deployment
